"""create buyer master

Revision ID: a0f206fbb2c6
Revises: ef16347c3623
Create Date: 2026-02-07 01:08:48.403952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0f206fbb2c6'
down_revision: Union[str, Sequence[str], None] = 'ef16347c3623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_code', sa.String(length=50), nullable=False),
    sa.Column('buyer_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='buyerstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_code')
    )
    op.create_index(op.f('ix_buyer_master_id'), 'buyer_master', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buyer_master_id'), table_name='buyer_master')
    op.drop_table('buyer_master')
    # ### end Alembic commands ###
