"""create size master

Revision ID: a47a2f03e539
Revises: f91901fd0513
Create Date: 2026-02-10 14:09:05.974650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47a2f03e539'
down_revision: Union[str, Sequence[str], None] = 'f91901fd0513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('size_master',
    sa.Column('size_id', sa.BigInteger(), nullable=False),
    sa.Column('size_code', sa.String(length=20), nullable=False),
    sa.Column('size_name', sa.String(length=50), nullable=False),
    sa.Column('size_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('size_id'),
    sa.UniqueConstraint('size_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('size_master')
    # ### end Alembic commands ###
