"""create style master

Revision ID: bf898fbdb24d
Revises: a0f206fbb2c6
Create Date: 2026-02-07 12:13:44.743701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf898fbdb24d'
down_revision: Union[str, Sequence[str], None] = 'a0f206fbb2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style_master',
    sa.Column('style_master_id', sa.BigInteger(), nullable=False),
    sa.Column('style_code', sa.BigInteger(), nullable=False),
    sa.Column('style_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='stylestatus'), nullable=False),
    sa.PrimaryKeyConstraint('style_master_id')
    )
    op.create_index(op.f('ix_style_master_style_code'), 'style_master', ['style_code'], unique=True)
    op.create_index(op.f('ix_style_master_style_master_id'), 'style_master', ['style_master_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_style_master_style_master_id'), table_name='style_master')
    op.drop_index(op.f('ix_style_master_style_code'), table_name='style_master')
    op.drop_table('style_master')
    # ### end Alembic commands ###
